[tool.bandit]
skips = ['B605']

[tool.codespell]
ignore-words-list = '.github/linters/codespell.txt'
skip = 'src/salam-wa.js,src/salam-wa.html'

[tool.isort]
profile = 'black'

[tool.vulture]
min_confidence = 100
paths = ['generated-config/', 'test/']
sort_by_size = true
