items:

  - type: AST_LAYOUT_ATTRIBUTE_TYPE_GROUP
    generate_name: "group"
    text:
      en: "group"
      fa: "گروه"

  - type: AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
    generate_name: "class"
    text:
      en: "class"
      fa: "کلاس"

  - type: AST_LAYOUT_ATTRIBUTE_TYPE_ID
    generate_name: "id"
    text:
      en: "id"
      fa: "شناسه"

  - type: AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
    generate_name: "content"
    text:
      en: "content"
      fa: "محتوا"

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_SRC, "SRC", "src", "src",
                          "منبع")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT, "REPEAT", "repeat",
                          "repeat", "تکرار")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_DIR, "DIR", "dir", "dir",
                          "جهت")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_LANG, "LANG", "lang",
                          "lang", "زبان")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_TITLE, "TITLE", "title",
                          "title", "عنوان")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_TYPE, "TYPE", "type",
                          "type", "نوع")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_AUTHOR, "AUTHOR", "author",
                          "author", "نویسنده")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_DESCRIPTION, "DESCRIPTION",
                          "description", "description", "توضیح")
ADD_LAYOUT_ATTRIBUTE_TYPE_REPEAT(AST_LAYOUT_ATTRIBUTE_TYPE_DESCRIPTION,
                                 "DESCRIPTION", "description", "description",
                                 "توضیحات")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_KEYWORDS, "KEYWORDS",
                          "keywords", "keywords", "کلمات")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_ICON, "ICON", "icon",
                          "icon", "نمایه")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_NAME, "NAME", "name",
                          "name", "نام")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_CHARSET, "CHARSET",
                          "charset", "charset", "فرمت متنی")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_REFRESH, "REFRESH",
                          "refresh", "refresh", "بروزرسانی")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_VIEWPORT, "VIEWPORT",
                          "viewport", "viewport", "محدوده نمایش")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_VALUE, "VALUE", "value",
                          "value", "مقدار")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_PLACEHOLDER, "PLACEHOLDER",
                          "placeholder", "placeholder", "راهنما")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_REQUIRED, "REQUIRED",
                          "required", "required", "اجباری")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_FONT_UNICODE_RANGE,
                          "UNICODE_RANGE", "unicode_range", "unicode-range",
                          "محدود یونیکد")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_FONT_WEIGHT, "FONT_WEIGHT",
                          "font_weight", "font-weight", "وزن")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_FONT_STYLE, "FONT_STYLE",
                          "font_style", "font-style", "سبک")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MAX_WIDTH,
                          "RESPONSIVE_MAX_WIDTH", "responsive_max_width",
                          "media-max-width", "شرط حداکثر عرض")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MAX_HEIGHT,
                          "RESPONSIVE_MAX_HEIGHT", "responsive_max_height",
                          "media-max-height", "شرط حداکثر ارتفاع")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MIN_WIDTH,
                          "RESPONSIVE_MIN_WIDTH", "responsive_min_width",
                          "media-min-width", "شرط حداقل عرض")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_RESPONSIVE_MIN_HEIGHT,
                          "RESPONSIVE_MIN_HEIGHT", "responsive_min_height",
                          "media-min-height", "شرط حداقل ارتفاع")

ADD_LAYOUT_ATTRIBUTE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_ERROR, "ERROR", "error", "",
                          "")
