items:
- id: inherit
  text:
    en:
    - inherit
    fa:
    - ارث بری
- id: initial
  text:
    en:
    - initial
    fa:
    - ابتدایی
- id: revert
  text:
    en:
    - revert
    fa:
    - بازگردانی
- id: revert-layer
  text:
    en:
    - revert-layer
    fa:
    - بازگردانی لایه
- id: unset
  text:
    en:
    - unset
    fa:
    - حذف شده
