items:
  - generate_name: ''
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ERROR
    text:
      fa:
        - ''
  - generate_name: '*'
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_GLOBAL
    text:
      en:
        - global
      fa:
        - سراسری
  - generate_name: hover
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_HOVER
    text:
      en:
        - hover
      fa:
        - هاور
  - generate_name: active
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ACTIVE
    text:
      en:
        - active
      fa:
        - فعال
  - generate_name: focus
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS
    text:
      en:
        - focus
      fa:
        - فوكوس
  - generate_name: visited
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VISITED
    text:
      en:
        - visited
      fa:
        - بازديد
  - generate_name: link
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LINK
    text:
      en:
        - link
      fa:
        - لينك
  - generate_name: focus-visible
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_VISIBLE
    text:
      en:
        - focus-visible
      fa:
        - فوكوس قابل مشاهده
  - generate_name: focus-within
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_WITHIN
    text:
      en:
        - focus-within
      fa:
        - فوكوس داخلي
  - generate_name: checked
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_CHECKED
    text:
      en:
        - checked
      fa:
        - انتخاب
  - generate_name: disabled
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_DISABLED
    text:
      en:
        - disabled
      fa:
        - غيرفعال
  - generate_name: enabled
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ENABLED
    text:
      en:
        - enabled
      fa:
        - فعال
  - generate_name: required
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_REQUIRED
    text:
      en:
        - required
      fa:
        - ضروري
  - generate_name: optional
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OPTIONAL
    text:
      en:
        - optional
      fa:
        - اختياري
  - generate_name: read-only
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_ONLY
    text:
      en:
        - read-only
      fa:
        - فقط خواندني
  - generate_name: read-write
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_WRITE
    text:
      en:
        - read-write
      fa:
        - قابل نوشتن
  - generate_name: valid
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VALID
    text:
      en:
        - valid
      fa:
        - معتبر
  - generate_name: invalid
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_INVALID
    text:
      en:
        - invalid
      fa:
        - نامعتبر
  - generate_name: in-range
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_IN_RANGE
    text:
      en:
        - in-range
      fa:
        - در محدوده
  - generate_name: out-of-range
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OUT_OF_RANGE
    text:
      en:
        - out-of-range
      fa:
        - خارج از محدوده
  - generate_name: placeholder-shown
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_PLACEHOLDER_SHOWN
    text:
      en:
        - placeholder-shown
      fa:
        - نمايش جايگير
  - generate_name: blank
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_BLANK
    text:
      en:
        - blank
      fa:
        - خالي
  - generate_name: target
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_TARGET
    text:
      en:
        - target
      fa:
        - هدف
  - generate_name: root
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ROOT
    text:
      en:
        - root
      fa:
        - ريشه
  - generate_name: nth-child
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_CHILD
    text:
      en:
        - nth-child
      fa:
        - فرزند nام
  - generate_name: nth-last-child
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_CHILD
    text:
      en:
        - nth-last-child
      fa:
        - آخرين فرزند nام
  - generate_name: nth-of-type
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_OF_TYPE
    text:
      en:
        - nth-of-type
      fa:
        - نوع nام
  - generate_name: nth-last-of-type
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_OF_TYPE
    text:
      en:
        - nth-last-of-type
      fa:
        - آخرين نوع nام
  - generate_name: first-child
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_CHILD
    text:
      en:
        - first-child
      fa:
        - اولين فرزند
  - generate_name: last-child
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_CHILD
    text:
      en:
        - last-child
      fa:
        - آخرين فرزند
  - generate_name: first-of-type
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_OF_TYPE
    text:
      en:
        - first-of-type
      fa:
        - اولين نوع
  - generate_name: last-of-type
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_OF_TYPE
    text:
      en:
        - last-of-type
      fa:
        - آخرين نوع
  - generate_name: only-child
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_CHILD
    text:
      en:
        - only-child
      fa:
        - تنها فرزند
  - generate_name: only-of-type
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_OF_TYPE
    text:
      en:
        - only-of-type
      fa:
        - تنها نوع
  - generate_name: empty
    id: AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_EMPTY
    text:
      en:
        - empty
      fa:
        - خالي
