items:
  - descriptions: ''
    examples: ''
    generate_name: a
    id: AST_LAYOUT_TYPE_LINK
    is_single: false
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_HREF
      - AST_LAYOUT_ATTRIBUTE_TYPE_TYPE
    text:
      en:
        - link
      fa:
        - پیوند
  - descriptions: ''
    examples: ''
    generate_name: ''
    id: AST_LAYOUT_TYPE_INCLUDE
    is_single: true
    text:
      en:
        - include
      fa:
        - بارگیری
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_SRC
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
  - descriptions: ''
    examples: ''
    generate_name: ''
    id: AST_LAYOUT_TYPE_ERROR
    is_single: true
    text:
      en:
        - error
      fa:
        - خطا
    attributes:
  - descriptions: ''
    examples: ''
    generate_name: ''
    id: AST_LAYOUT_TYPE_LAYOUT
    is_single: false
    text:
      en:
        - layout
      fa:
        - صفحه
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
      - AST_LAYOUT_ATTRIBUTE_TYPE_TITLE
      - AST_LAYOUT_ATTRIBUTE_TYPE_LANG
      - AST_LAYOUT_ATTRIBUTE_TYPE_DIR
      - AST_LAYOUT_ATTRIBUTE_TYPE_AUTHOR
      - AST_LAYOUT_ATTRIBUTE_TYPE_DESCRIPTION
      - AST_LAYOUT_ATTRIBUTE_TYPE_KEYWORDS
      - AST_LAYOUT_ATTRIBUTE_TYPE_ICON
      - AST_LAYOUT_ATTRIBUTE_TYPE_CHARSET
      - AST_LAYOUT_ATTRIBUTE_TYPE_REFRESH
      - AST_LAYOUT_ATTRIBUTE_TYPE_VIEWPORT
  - descriptions: ''
    examples: ''
    generate_name: div
    id: AST_LAYOUT_TYPE_DIV
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
    is_single: false
    text:
      en:
        - box
        - div
      fa:
        - جعبه
  - descriptions: ''
    examples: ''
    generate_name: p
    id: AST_LAYOUT_TYPE_PARAGRAPH
    is_single: false
    text:
      en:
        - paragraph
      fa:
        - پاراگراف
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
  - descriptions: ''
    examples: ''
    generate_name: button
    id: AST_LAYOUT_TYPE_BUTTON
    is_single: false
    text:
      en:
        - button
      fa:
        - دکمه
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_ALERT
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
      - AST_LAYOUT_ATTRIBUTE_TYPE_NAME
  - descriptions: ''
    examples: ''
    generate_name: textarea
    id: AST_LAYOUT_TYPE_TEXTAREA
    is_single: false
    text:
      en:
        - textarea
      fa:
        - ویرایشگرمتن
        - ویرایشگر متن
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_NAME
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
      - AST_LAYOUT_ATTRIBUTE_TYPE_PLACEHOLDER
  - descriptions: ''
    examples: ''
    generate_name: label
    id: AST_LAYOUT_TYPE_LABEL
    is_single: false
    text:
      en:
        - label
      fa:
        - برچسب
  - descriptions: ''
    examples: ''
    generate_name: select
    id: AST_LAYOUT_TYPE_SELECT
    is_single: false
    text:
      en:
        - select
      fa:
        - فهرست کشویی
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_NAME
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
  - descriptions: ''
    examples: ''
    generate_name: fieldset
    id: AST_LAYOUT_TYPE_FIELDSET
    is_single: false
    text:
      en:
        - fieldset
      fa:
        - گروه‌بندی
        - گروه بندی
  - descriptions: ''
    examples: ''
    generate_name: legend
    id: AST_LAYOUT_TYPE_LEGEND
    is_single: false
    text:
      en:
        - legend
      fa:
        - عنوان گروه
  - descriptions:
      fa: 'برای ارسال درخواست ها ما ورودی هارا داخل فرم ها قرار میدهیم تا مقدار انهارا گرفته و به ادرس مورد نظر ارسال کند'
    examples:
      fa:
        title: مثال ۱
        code: 'صفحه: فرم: نوع=«GET» منبع=«https://yourapi.ir» روش=«» تمام تمام'
    generate_name: form
    id: AST_LAYOUT_TYPE_FORM
    is_single: false
    text:
      en:
        - form
      fa:
        - فرم
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_SRC
      - AST_LAYOUT_ATTRIBUTE_TYPE_TYPE
      - AST_LAYOUT_ATTRIBUTE_TYPE_KIND
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
  - descriptions: ''
    examples: ''
    generate_name: optgroup
    id: AST_LAYOUT_TYPE_OPTGROUP
    is_single: false
    text:
      en:
        - optgroup
      fa:
        - گروه انتخاب
  - descriptions: ''
    examples: ''
    generate_name: datalist
    id: AST_LAYOUT_TYPE_DATALIST
    is_single: false
    text:
      en:
        - datalist
      fa:
        - داده فهرست
  - descriptions: ''
    examples: ''
    generate_name: span
    id: AST_LAYOUT_TYPE_SPAN
    is_single: false
    text:
      en:
        - span
      fa:
        - قطعه
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
  - descriptions: ''
    examples: ''
    generate_name: strong
    id: AST_LAYOUT_TYPE_STRONG
    is_single: false
    text:
      en:
        - strong
      fa:
        - ضخیم مهم
  - descriptions: ''
    examples: ''
    generate_name: em
    id: AST_LAYOUT_TYPE_EM
    is_single: false
    text:
      en:
        - em
      fa:
        - ایتالیک پیشرفته
  - descriptions: ''
    examples: ''
    generate_name: i
    id: AST_LAYOUT_TYPE_ITALIC
    is_single: false
    text:
      en:
        - italic
      fa:
        - ایتالیک
  - descriptions: ''
    examples: ''
    generate_name: b
    id: AST_LAYOUT_TYPE_BOLD
    is_single: false
    text:
      en:
        - bold
      fa:
        - ضخیم
        - درشت
  - descriptions: ''
    examples: ''
    generate_name: u
    id: AST_LAYOUT_TYPE_UNDERLINE
    is_single: false
    text:
      en:
        - underline
      fa:
        - زیرخط
        - زیر خط
  - descriptions: ''
    examples: ''
    generate_name: sub
    id: AST_LAYOUT_TYPE_SUB
    is_single: false
    text:
      en:
        - sub
      fa:
        - زیرین
  - descriptions: ''
    examples: ''
    generate_name: sup
    id: AST_LAYOUT_TYPE_SUP
    is_single: false
    text:
      en:
        - sup
      fa:
        - رویین
  - descriptions: ''
    examples: ''
    generate_name: s
    id: AST_LAYOUT_TYPE_S
    is_single: false
    text:
      en:
        - s
      fa:
        - خط خورده
  - descriptions: ''
    examples: ''
    generate_name: header
    id: AST_LAYOUT_TYPE_HEADER
    is_single: false
    text:
      en:
        - header
      fa:
        - سربخش
        - سر بخش
  - descriptions: ''
    examples: ''
    generate_name: footer
    id: AST_LAYOUT_TYPE_FOOTER
    is_single: false
    text:
      en:
        - footer
      fa:
        - پاصفحه
        - پا صفحه
  - descriptions: ''
    examples: ''
    generate_name: nav
    id: AST_LAYOUT_TYPE_NAV
    is_single: false
    text:
      en:
        - nav
      fa:
        - ناوبری
  - descriptions: ''
    examples: ''
    generate_name: section
    id: AST_LAYOUT_TYPE_SECTION
    is_single: false
    text:
      en:
        - section
      fa:
        - بخش
  - descriptions: ''
    examples: ''
    generate_name: article
    id: AST_LAYOUT_TYPE_ARTICLE
    is_single: false
    text:
      en:
        - article
      fa:
        - مقاله
  - descriptions: ''
    examples: ''
    generate_name: aside
    id: AST_LAYOUT_TYPE_ASIDE
    is_single: false
    text:
      en:
        - aside
      fa:
        - جداگانه
        - جدا گانه
  - descriptions: ''
    examples: ''
    generate_name: main
    id: AST_LAYOUT_TYPE_MAIN
    is_single: false
    text:
      en:
        - main
      fa:
        - اصلی
  - descriptions: ''
    examples: ''
    generate_name: figure
    id: AST_LAYOUT_TYPE_FIGURE
    is_single: false
    text:
      en:
        - figure
      fa:
        - شکل
  - descriptions: ''
    examples: ''
    generate_name: figcaption
    id: AST_LAYOUT_TYPE_FIGCAPTION
    is_single: false
    text:
      en:
        - figcaption
      fa:
        - زیرنویس شکل
        - زیر نویس شکل
  - descriptions: ''
    examples: ''
    generate_name: video
    id: AST_LAYOUT_TYPE_VIDEO
    is_single: false
    text:
      en:
        - video
      fa:
        - فیلم
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_SRC
  - descriptions: ''
    examples: ''
    generate_name: audio
    id: AST_LAYOUT_TYPE_AUDIO
    is_single: false
    text:
      en:
        - audio
      fa:
        - صدا
  - descriptions: ''
    examples: ''
    generate_name: iframe
    id: AST_LAYOUT_TYPE_IFRAME
    is_single: false
    text:
      en:
        - iframe
      fa:
        - سایت
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_WIDTH
      - AST_LAYOUT_ATTRIBUTE_TYPE_HEIGHT
      - AST_LAYOUT_ATTRIBUTE_TYPE_TITLE
      - AST_LAYOUT_ATTRIBUTE_TYPE_SRC
  - descriptions: ''
    examples: ''
    generate_name: style
    id: AST_LAYOUT_TYPE_STYLE
    is_single: false
    text:
      en:
        - style
      fa:
        - ظاهر سفارشی
  - descriptions: ''
    examples: ''
    generate_name: canvas
    id: AST_LAYOUT_TYPE_CANVAS
    is_single: false
    text:
      en:
        - canvas
      fa:
        - گرافیکی
  - descriptions: ''
    examples: ''
    generate_name: ul
    id: AST_LAYOUT_TYPE_UL
    is_single: false
    text:
      en:
        - ul
      fa:
        - فهرست غیرمرتب
        - فهرست غیر مرتب
        - فهرست نامرتب
        - فهرست نا مرتب
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
  - descriptions: ''
    examples: ''
    generate_name: ol
    id: AST_LAYOUT_TYPE_OL
    is_single: false
    text:
      en:
        - ol
      fa:
        - فهرست مرتب
  - descriptions: ''
    examples: ''
    generate_name: 'option'
    id: AST_LAYOUT_TYPE_OPTION
    is_single: false
    text:
      en:
        - item
      fa:
        - مورد
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
  - descriptions: ''
    examples: ''
    generate_name: li
    id: AST_LAYOUT_TYPE_LI
    is_single: false
    text:
      en:
        - li
      fa:
        - مورد
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_CONTENT
      - AST_LAYOUT_ATTRIBUTE_TYPE_REPEAT
  - descriptions: ''
    examples: ''
    generate_name: table
    id: AST_LAYOUT_TYPE_TABLE
    is_single: false
    text:
      en:
        - table
      fa:
        - جدول
  - descriptions: ''
    examples: ''
    generate_name: thead
    id: AST_LAYOUT_TYPE_TABLE_HEADER
    is_single: false
    text:
      en:
        - table-header
      fa:
        - سرجدول
        - سر جدول
  - descriptions: ''
    examples: ''
    generate_name: tfoot
    id: AST_LAYOUT_TYPE_TABLE_FOOTER
    is_single: false
    text:
      en:
        - table-footer
      fa:
        - پاصفحه جدول
        - پا صفحه جدول
  - descriptions: ''
    examples: ''
    generate_name: tr
    id: AST_LAYOUT_TYPE_TABLE_TR
    is_single: false
    text:
      en:
        - table-tr
      fa:
        - ردیف
  - descriptions: ''
    examples: ''
    generate_name: td
    id: AST_LAYOUT_TYPE_TABLE_TD
    is_single: false
    text:
      en:
        - table-td
      fa:
        - سلول
  - descriptions: ''
    examples: ''
    generate_name: th
    id: AST_LAYOUT_TYPE_TABLE_TH
    is_single: false
    text:
      en:
        - table-th
      fa:
        - سرسلول
        - سر سلول
  - descriptions: ''
    examples: ''
    generate_name: caption
    id: AST_LAYOUT_TYPE_CAPTION
    is_single: false
    text:
      en:
        - caption
      fa:
        - عنوان جدول
  - descriptions: ''
    examples: ''
    generate_name: th
    id: AST_LAYOUT_TYPE_COL
    is_single: false
    text:
      en:
        - col
      fa:
        - ستون
  - descriptions: ''
    examples: ''
    generate_name: br
    id: AST_LAYOUT_TYPE_BR
    is_single: true
    text:
      en:
        - br
      fa:
        - خط بعدی
  - descriptions: ''
    examples: ''
    generate_name: hr
    id: AST_LAYOUT_TYPE_HR
    is_single: true
    text:
      en:
        - hr
      fa:
        - خط
  - descriptions: ''
    examples: ''
    generate_name: input
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_VALUE
      - AST_LAYOUT_ATTRIBUTE_TYPE_NAME
      - AST_LAYOUT_ATTRIBUTE_TYPE_PLACEHOLDER
    id: AST_LAYOUT_TYPE_INPUT
    is_single: false
    text:
      en:
        - input
      fa:
        - ورودی
  - descriptions: ''
    examples: ''
    generate_name: img
    id: AST_LAYOUT_TYPE_IMG
    is_single: true
    text:
      en:
        - img
      fa:
        - تصویر
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_ID
      - AST_LAYOUT_ATTRIBUTE_TYPE_CLASS
      - AST_LAYOUT_ATTRIBUTE_TYPE_SRC
  - descriptions: 'اسکریپت سفارشی جهت لود کدهای جاوا اسکریپت'
    examples: ''
    generate_name: script
    id: AST_LAYOUT_TYPE_SCRIPT
    is_single: false
    text:
      en:
        - script
      fa:
        - اسکریپت
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_SRC
  - descriptions: ''
    examples: ''
    generate_name: font
    attributes:
      - AST_LAYOUT_ATTRIBUTE_TYPE_FONT_NAME
      - AST_LAYOUT_ATTRIBUTE_TYPE_FONT_SRC
      - AST_LAYOUT_ATTRIBUTE_TYPE_FONT_UNICODE_RANGE
      - AST_LAYOUT_ATTRIBUTE_TYPE_FONT_STYLE
      - AST_LAYOUT_ATTRIBUTE_TYPE_FONT_WEIGHT
    id: AST_LAYOUT_TYPE_FONT
    is_single: false
    text:
      en:
        - font
      fa:
        - قلم
  - descriptions: ''
    examples: ''
    generate_name: '@media'
    id: AST_LAYOUT_TYPE_MEDIA
    is_single: false
    text:
      en:
        - responsive
      fa:
        - واکنش گرا
        - واکنش‌گرا
