name: ğŸ§ª Test make run
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  make-run:
    name: ğŸ› ï¸ Run `make run`
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v5
      - name: ğŸ“¦ Install dependencies
        run: sudo apt-get install build-essential
      - name: ğŸ·ï¸ GCC Version
        run: |
          gcc --version
      - name: ğŸ› ï¸ Build Salam for Linux
        run: |
          make run
